# Build astropy cosmologies from Abacus Metadata

In [29]:
from all_cosmo import read_files

file_names, cosmo_names, cosmo_tags = read_files("../data")

In [30]:
print(file_names)

['pairs_AbacusSummit_base_c165_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c103_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c151_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c179_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c137_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c003_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c160_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c148_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c106_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c154_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c132_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c164_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c102_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c180_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c150_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c136_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c178_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c002_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c161_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c107_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c149_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c155_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c133_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c167_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c101_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c153_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c135_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c001_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c162_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c018_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c104_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c118_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c156_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c004_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c130_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c166_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c100_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c152_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c134_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c000_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c163_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c019_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c105_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c157_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c119_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c131_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c142_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c124_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c010_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c138_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c176_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c110_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c109_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c147_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c015_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c121_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c173_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c009_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c115_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c143_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c125_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c177_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c139_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c111_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c146_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c108_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c014_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c120_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c172_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c020_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c114_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c140_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c168_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c126_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c012_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c174_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c112_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c145_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c017_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c123_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c171_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c117_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c141_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c169_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c013_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c175_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c113_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c144_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c016_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c122_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c170_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c116_ph000_z0.100.hdf5', 'pairs_AbacusSummit_base_c158_ph000_z0.100.hdf5']

In [31]:
print(cosmo_tags)

['c165', 'c103', 'c151', 'c179', 'c137', 'c003', 'c160', 'c148', 'c106', 'c154', 'c132', 'c164', 'c102', 'c180', 'c150', 'c136', 'c178', 'c002', 'c161', 'c107', 'c149', 'c155', 'c133', 'c167', 'c101', 'c153', 'c135', 'c001', 'c162', 'c018', 'c104', 'c118', 'c156', 'c004', 'c130', 'c166', 'c100', 'c152', 'c134', 'c000', 'c163', 'c019', 'c105', 'c157', 'c119', 'c131', 'c142', 'c124', 'c010', 'c138', 'c176', 'c110', 'c109', 'c147', 'c015', 'c121', 'c173', 'c009', 'c115', 'c143', 'c125', 'c177', 'c139', 'c111', 'c146', 'c108', 'c014', 'c120', 'c172', 'c020', 'c114', 'c140', 'c168', 'c126', 'c012', 'c174', 'c112', 'c145', 'c017', 'c123', 'c171', 'c117', 'c141', 'c169', 'c013', 'c175', 'c113', 'c144', 'c016', 'c122', 'c170', 'c116', 'c158']

In [32]:
print(cosmo_names)

['AbacusSummit_base_c165_ph000', 'AbacusSummit_base_c103_ph000', 'AbacusSummit_base_c151_ph000', 'AbacusSummit_base_c179_ph000', 'AbacusSummit_base_c137_ph000', 'AbacusSummit_base_c003_ph000', 'AbacusSummit_base_c160_ph000', 'AbacusSummit_base_c148_ph000', 'AbacusSummit_base_c106_ph000', 'AbacusSummit_base_c154_ph000', 'AbacusSummit_base_c132_ph000', 'AbacusSummit_base_c164_ph000', 'AbacusSummit_base_c102_ph000', 'AbacusSummit_base_c180_ph000', 'AbacusSummit_base_c150_ph000', 'AbacusSummit_base_c136_ph000', 'AbacusSummit_base_c178_ph000', 'AbacusSummit_base_c002_ph000', 'AbacusSummit_base_c161_ph000', 'AbacusSummit_base_c107_ph000', 'AbacusSummit_base_c149_ph000', 'AbacusSummit_base_c155_ph000', 'AbacusSummit_base_c133_ph000', 'AbacusSummit_base_c167_ph000', 'AbacusSummit_base_c101_ph000', 'AbacusSummit_base_c153_ph000', 'AbacusSummit_base_c135_ph000', 'AbacusSummit_base_c001_ph000', 'AbacusSummit_base_c162_ph000', 'AbacusSummit_base_c018_ph000', 'AbacusSummit_base_c104_ph000', 'AbacusSummit_base_c118_ph000', 'AbacusSummit_base_c156_ph000', 'AbacusSummit_base_c004_ph000', 'AbacusSummit_base_c130_ph000', 'AbacusSummit_base_c166_ph000', 'AbacusSummit_base_c100_ph000', 'AbacusSummit_base_c152_ph000', 'AbacusSummit_base_c134_ph000', 'AbacusSummit_base_c000_ph000', 'AbacusSummit_base_c163_ph000', 'AbacusSummit_base_c019_ph000', 'AbacusSummit_base_c105_ph000', 'AbacusSummit_base_c157_ph000', 'AbacusSummit_base_c119_ph000', 'AbacusSummit_base_c131_ph000', 'AbacusSummit_base_c142_ph000', 'AbacusSummit_base_c124_ph000', 'AbacusSummit_base_c010_ph000', 'AbacusSummit_base_c138_ph000', 'AbacusSummit_base_c176_ph000', 'AbacusSummit_base_c110_ph000', 'AbacusSummit_base_c109_ph000', 'AbacusSummit_base_c147_ph000', 'AbacusSummit_base_c015_ph000', 'AbacusSummit_base_c121_ph000', 'AbacusSummit_base_c173_ph000', 'AbacusSummit_base_c009_ph000', 'AbacusSummit_base_c115_ph000', 'AbacusSummit_base_c143_ph000', 'AbacusSummit_base_c125_ph000', 'AbacusSummit_base_c177_ph000', 'AbacusSummit_base_c139_ph000', 'AbacusSummit_base_c111_ph000', 'AbacusSummit_base_c146_ph000', 'AbacusSummit_base_c108_ph000', 'AbacusSummit_base_c014_ph000', 'AbacusSummit_base_c120_ph000', 'AbacusSummit_base_c172_ph000', 'AbacusSummit_base_c020_ph000', 'AbacusSummit_base_c114_ph000', 'AbacusSummit_base_c140_ph000', 'AbacusSummit_base_c168_ph000', 'AbacusSummit_base_c126_ph000', 'AbacusSummit_base_c012_ph000', 'AbacusSummit_base_c174_ph000', 'AbacusSummit_base_c112_ph000', 'AbacusSummit_base_c145_ph000', 'AbacusSummit_base_c017_ph000', 'AbacusSummit_base_c123_ph000', 'AbacusSummit_base_c171_ph000', 'AbacusSummit_base_c117_ph000', 'AbacusSummit_base_c141_ph000', 'AbacusSummit_base_c169_ph000', 'AbacusSummit_base_c013_ph000', 'AbacusSummit_base_c175_ph000', 'AbacusSummit_base_c113_ph000', 'AbacusSummit_base_c144_ph000', 'AbacusSummit_base_c016_ph000', 'AbacusSummit_base_c122_ph000', 'AbacusSummit_base_c170_ph000', 'AbacusSummit_base_c116_ph000', 'AbacusSummit_base_c158_ph000']

In [33]:
import pandas as pd
cosmo_df = pd.DataFrame({
    'Cosmology': cosmo_names,
    'File_name': file_names},
    index=cosmo_tags
)

In [34]:
cosmo_df.loc['c000']['Cosmology']

'AbacusSummit_base_c000_ph000'

In [35]:
from astropy.cosmology import w0waCDM
import abacusnbody.metadata

meta_time_indp = abacusnbody.metadata.get_meta(cosmo_df.loc['c000']['Cosmology'])
meta = abacusnbody.metadata.get_meta(cosmo_df.loc['c000']['Cosmology'],redshift=0.1)

cosmo = w0waCDM(H0=meta_time_indp['H0'],
                Om0=meta_time_indp['Omega_M'], 
                Ode0=meta_time_indp['Omega_DE'], 
                Ob0=meta_time_indp['omega_b'],
                w0=meta_time_indp['w0'], 
                wa=meta_time_indp['wa'],
                Neff=meta_time_indp['N_ur']+meta_time_indp['N_ncdm'],
                Tcmb0=2.7255)
print(cosmo)

w0waCDM(H0=67.36 km / (Mpc s), Om0=0.315192, Ode0=0.684808, Tcmb0=2.7255 K, Neff=3.0328, m_nu=[0. 0. 0.] eV, Ob0=0.02237, w0=-1.0, wa=0.0)

In [36]:
cosmo.Om(0.1)

np.float64(0.37987939971487905)

In [37]:
meta['OmegaNow_m']

0.379887444945823

In [38]:
cosmo.Om(0)

np.float64(0.315192)

In [39]:
meta['Omega_M']

0.315192

In [40]:
for key in meta_time_indp.keys():
    print(key)

A_s
AllowGroupFinding
BackupDirectory
BackupStepInterval
BoxSize
CLASS_Redshift
CPD
Conv_IOCores
Conv_IOMode
Conv_OMP_NUM_THREADS
Conv_OMP_PLACES
Conv_OMP_PROC_BIND
Conv_zwidth
ConvolutionCacheSizeMB
ConvolutionL1CacheSizeMB
DeleteICsAfterFirstBackup
DensityKernelRad
DerivativeExpansionRadius
DerivativesDirectory
DirectBPD
FinalRedshift
FoFLinkingLength
GPUQueueAssignments
GPUThreadCoreStart
GroupDirectory
GroupRadius
GrowthTable
H0
ICFormat
ICPositionRange
ICVelocity2Displacement
IC_truncated_bits
IOCores
InitialConditionsDirectory
InitialRedshift
L0DensityThreshold
L1OutputRedshifts
LagrangianPTOrder
LightConeDirectory
LightConeOrigins
LocalWorkingDirectory
LogDirectory
LogVerbosity
MicrostepTimeStep
MinL1HaloNP
MultipoleDirectory
MunmapThreadCore
NGPUThreadCores
NLightCones
NP
N_ncdm
N_ur
NearFieldRadius
NumSlabsInsertList
NumSlabsInsertListIC
OMP_NUM_THREADS
OMP_PLACES
OMP_PROC_BIND
Omega_DE
Omega_K
Omega_M
Omega_Smooth
Order
OutputDirectory
OutputFormat
Parallel
ParticleSubsampleA
ParticleSubsampleB
PowerSpectrumN1d
PowerSpectrumStepInterval
ProperSoftening
RamDisk
SODensity
SO_EvolvingThreshold
SO_alpha_eligible
SimComment
SimName
SimSet
SiteName
SofteningLength
SofteningMax
StateIOMode
TaylorDirectory
TimeSliceRedshifts
TimeSliceRedshifts_Subsample
TimeStepAccel
TimeStepDlna
WorkingDirectory
ZD_CornerModes
ZD_NumBlock
ZD_PLT_filename
ZD_PLT_target_z
ZD_Pk_file_redshift
ZD_Pk_filename
ZD_Pk_norm
ZD_Pk_scale
ZD_Pk_sigma_ratio
ZD_Pk_smooth
ZD_Seed
ZD_Version
ZD_f_cluster
ZD_k_cutoff
ZD_mpirun_cmd
ZD_qPLT
ZD_qPLT_rescale
ZD_qdensity
ZeldovichDirectory
alpha_s
checkpoint_timeout
hMpc
mpirun_cmd
n_s
omega_b
omega_cdm
omega_ncdm
step_timeout
w0
wa
CLASS_power_spectrum

In [41]:
for key in meta.keys():
    print(key)

A_s
AllowGroupFinding
BackupDirectory
BackupStepInterval
BoxSize
CLASS_Redshift
CPD
Conv_IOCores
Conv_IOMode
Conv_OMP_NUM_THREADS
Conv_OMP_PLACES
Conv_OMP_PROC_BIND
Conv_zwidth
ConvolutionCacheSizeMB
ConvolutionL1CacheSizeMB
DeleteICsAfterFirstBackup
DensityKernelRad
DerivativeExpansionRadius
DerivativesDirectory
DirectBPD
FinalRedshift
FoFLinkingLength
GPUQueueAssignments
GPUThreadCoreStart
GroupDirectory
GroupRadius
GrowthTable
H0
ICFormat
ICPositionRange
ICVelocity2Displacement
IC_truncated_bits
IOCores
InitialConditionsDirectory
InitialRedshift
L0DensityThreshold
L1OutputRedshifts
LagrangianPTOrder
LightConeDirectory
LightConeOrigins
LocalWorkingDirectory
LogDirectory
LogVerbosity
MicrostepTimeStep
MinL1HaloNP
MultipoleDirectory
MunmapThreadCore
NGPUThreadCores
NLightCones
NP
N_ncdm
N_ur
NearFieldRadius
NumSlabsInsertList
NumSlabsInsertListIC
OMP_NUM_THREADS
OMP_PLACES
OMP_PROC_BIND
Omega_DE
Omega_K
Omega_M
Omega_Smooth
Order
OutputDirectory
OutputFormat
Parallel
ParticleSubsampleA
ParticleSubsampleB
PowerSpectrumN1d
PowerSpectrumStepInterval
ProperSoftening
RamDisk
SODensity
SO_EvolvingThreshold
SO_alpha_eligible
SimComment
SimName
SimSet
SiteName
SofteningLength
SofteningMax
StateIOMode
TaylorDirectory
TimeSliceRedshifts
TimeSliceRedshifts_Subsample
TimeStepAccel
TimeStepDlna
WorkingDirectory
ZD_CornerModes
ZD_NumBlock
ZD_PLT_filename
ZD_PLT_target_z
ZD_Pk_file_redshift
ZD_Pk_filename
ZD_Pk_norm
ZD_Pk_scale
ZD_Pk_sigma_ratio
ZD_Pk_smooth
ZD_Seed
ZD_Version
ZD_f_cluster
ZD_k_cutoff
ZD_mpirun_cmd
ZD_qPLT
ZD_qPLT_rescale
ZD_qdensity
ZeldovichDirectory
alpha_s
checkpoint_timeout
hMpc
mpirun_cmd
n_s
omega_b
omega_cdm
omega_ncdm
step_timeout
w0
wa
CLASS_power_spectrum
BoxSizeHMpc
BoxSizeMpc
CodeVersion
CoordinateDistanceHMpc
DeltaEtaDrift
DeltaRedshift
DeltaScaleFactor
DeltaTime
DensityKernelRad2
Do2LPTVelocityRereading
DoublePrecision
FirstHalfEtaKick
FullStepNumber
Growth
Growth_on_a_n
Htime
HubbleNow
HubbleTimeGyr
HubbleTimeHGyr
LPTStepNumber
LastHalfEtaKick
MachineName
NodeRank
NodeSize
OmegaNow_DE
OmegaNow_K
OmegaNow_m
OutputFormatVersion
OutputType
ParameterFileName
ParticleMassHMsun
ParticleMassMsun
Pipeline
Redshift
RunTime
SODensityL1
SODensityL2
ScaleFactor
ScaleFactorHalf
SofteningLengthNow
SofteningLengthNowInternal
SofteningType
Time
VelZSpace_to_Canonical
VelZSpace_to_kms
etaD
etaK
f_growth
fsmooth
ppd
w

# Extract Abacus cosmologies from csv

In [42]:
cosmo_params_df = pd.read_csv('cosmologies.csv')

len(cosmo_params_df), len(cosmo_tags)

(98, 93)

In [43]:
cosmo_numbers = [int(tag[1:]) for tag in cosmo_tags]

cosmo_params_df['number'] = cosmo_params_df['root'].str.extract(r'(\d+)$').astype(int)

filtered_cosmo = cosmo_params_df[cosmo_params_df['number'].isin(cosmo_numbers)]

filtered_cosmo = filtered_cosmo.drop(columns=['number'])

len(filtered_cosmo)

93

In [44]:
cosmo_tags.sort()
filtered_cosmo.index = cosmo_tags
filtered_cosmo.index.name = 'cosmo'
filtered_cosmo.drop(columns=['root'], inplace=True)
filtered_cosmo

,notes,omega_b,omega_cdm,h,A_s,n_s,alpha_s,N_ur,N_ncdm,omega_ncdm,w0_fld,wa_fld,sigma8_m,sigma8_cb
cosmo,,,,,,,,,,,,,,
c000,"BaselineLCDM,Planck2018base_plikHM_TTTEEE_lowl...",0.02237,0.1200,0.6736,2.083000e-09,0.9649,0.000,2.0328,1,0.000644,-1.000,0.000,0.807952,0.811355
c001,"WMAP9+ACT+SPTLCDM,Calabrese++2017",0.02242,0.1134,0.7030,2.037600e-09,0.9638,0.000,2.0328,1,0.000644,-1.000,0.000,0.776779,0.780222
c002,"wCDMwiththawingmodelw0=-0.7,wa=-0.5",0.02237,0.1200,0.6278,2.314000e-09,0.9649,0.000,2.0328,1,0.000644,-0.700,-0.500,0.808189,0.811577
c003,"Neff=3.70,frombase_nnu_plikHM_TT_lowl_lowE_Rie...",0.02260,0.1291,0.7160,2.243800e-09,0.9876,0.000,2.6868,1,0.000644,-1.000,0.000,0.855190,0.858583
c004,"Lowsigma8_matter=0.75,otherwiseBaselineLCDM",0.02237,0.1200,0.6736,1.794900e-09,0.9649,0.000,2.0328,1,0.000644,-1.000,0.000,0.749999,0.753159
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
c176,Emulatorgridaroundbaselinecosmology,0.02238,0.1199,0.6972,2.312000e-09,0.9459,0.036,1.9043,1,0.000644,-1.222,0.339,0.892483,0.896318
c177,Emulatorgridaroundbaselinecosmology,0.02239,0.1344,0.6820,2.064100e-09,1.0002,0.007,2.8643,1,0.000644,-0.757,-0.443,0.806026,0.809110
c178,Emulatorgridaroundbaselinecosmology,0.02234,0.1204,0.6542,1.966500e-09,0.9424,0.037,1.8987,1,0.000644,-0.874,-0.455,0.791239,0.794555
c179,Emulatorgridaroundbaselinecosmology,0.02240,0.1067,0.5881,2.236500e-09,0.9308,-0.003,1.1884,1,0.000644,-0.755,-0.435,0.775969,0.779541
c180,Emulatorgridaroundbaselinecosmology,0.02258,0.1209,0.7451,2.279000e-09,0.9796,-0.034,2.1722,1,0.000644,-1.108,-0.274,0.894071,0.897833

In [45]:
latex_columns = {
    'root': 'Cosmology',
    'notes': 'Notes',
    'omega_b' : r'$\Omega_b$',
    'omega_cdm' : r'$\Omega_c$',
    'h': r'$h$',
    'A_s': r'$A_s$',
    'n_s': r'$n_s$',
    'alpha_s': r'$\alpha_s$',
    'N_ur': r'$N_{ur}$',
    'N_ncdm': r'$N_{ncdm}$',
    'omega_ncdm': r'$\Omega_{ncdm}$',
    'w0_fld': r'$w_0$',
    'wa_fld': r'$w_a$',
    'sigma8_m': r'$\sigma_8$',
    'sigma8_cb': r'$\sigma_{8,cb}$',
}

filtered_cosmo_renamed = filtered_cosmo.rename(columns=latex_columns)

filtered_cosmo_renamed.to_csv('filtered_cosmologies_latex_final.csv')

In [46]:
filtered_cosmo_renamed

,Notes,$\Omega_b$,$\Omega_c$,$h$,$A_s$,$n_s$,$\alpha_s$,$N_{ur}$,$N_{ncdm}$,$\Omega_{ncdm}$,$w_0$,$w_a$,$\sigma_8$,"$\sigma_{8,cb}$"
cosmo,,,,,,,,,,,,,,
c000,"BaselineLCDM,Planck2018base_plikHM_TTTEEE_lowl...",0.02237,0.1200,0.6736,2.083000e-09,0.9649,0.000,2.0328,1,0.000644,-1.000,0.000,0.807952,0.811355
c001,"WMAP9+ACT+SPTLCDM,Calabrese++2017",0.02242,0.1134,0.7030,2.037600e-09,0.9638,0.000,2.0328,1,0.000644,-1.000,0.000,0.776779,0.780222
c002,"wCDMwiththawingmodelw0=-0.7,wa=-0.5",0.02237,0.1200,0.6278,2.314000e-09,0.9649,0.000,2.0328,1,0.000644,-0.700,-0.500,0.808189,0.811577
c003,"Neff=3.70,frombase_nnu_plikHM_TT_lowl_lowE_Rie...",0.02260,0.1291,0.7160,2.243800e-09,0.9876,0.000,2.6868,1,0.000644,-1.000,0.000,0.855190,0.858583
c004,"Lowsigma8_matter=0.75,otherwiseBaselineLCDM",0.02237,0.1200,0.6736,1.794900e-09,0.9649,0.000,2.0328,1,0.000644,-1.000,0.000,0.749999,0.753159
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
c176,Emulatorgridaroundbaselinecosmology,0.02238,0.1199,0.6972,2.312000e-09,0.9459,0.036,1.9043,1,0.000644,-1.222,0.339,0.892483,0.896318
c177,Emulatorgridaroundbaselinecosmology,0.02239,0.1344,0.6820,2.064100e-09,1.0002,0.007,2.8643,1,0.000644,-0.757,-0.443,0.806026,0.809110
c178,Emulatorgridaroundbaselinecosmology,0.02234,0.1204,0.6542,1.966500e-09,0.9424,0.037,1.8987,1,0.000644,-0.874,-0.455,0.791239,0.794555
c179,Emulatorgridaroundbaselinecosmology,0.02240,0.1067,0.5881,2.236500e-09,0.9308,-0.003,1.1884,1,0.000644,-0.755,-0.435,0.775969,0.779541
c180,Emulatorgridaroundbaselinecosmology,0.02258,0.1209,0.7451,2.279000e-09,0.9796,-0.034,2.1722,1,0.000644,-1.108,-0.274,0.894071,0.897833